# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do
    setup_circle_ci
  end
  lane :increment_version do
    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: "1//0eamg-kDNxPp2CgYIARAAGA4SNwF-L9IrHU-TgKHVOWfaWEm_oAxH1v9gxshxggNcM_XcddV7YwNsQg3K2EpDLSy1CuWWV3-eROo"
    )
    increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
  end

  desc "Android Staging"
  lane :android_staging do

    increment_version

    gradle(task: "clean assembleStagingRelease")
  
    gradle(
      task: 'assembleStaging',
      build_type: 'Release'
    )


    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      groups: ENV["GROUPS"],
      release_notes: ENV["COMMIT_MESSAGE"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleStagingRelease")
  #   upload_to_play_store
  # end
end
