name: IOS Staging Build

on:
  workflow_dispatch:
  release:
    types: [published] # only run the workflow when a new release has been published
  push:
    branches: ["staging"]

jobs:
  ios-build:
    name: IOS Staging Build
    runs-on: macos-10.15
    defaults:
      run:
        working-directory: ios

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6
          bundler-cache: true

      - name: Restore Pods cache
        uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: bundle install && bundle exec pod install --repo-update && cd ..

      - name: Build IOS App
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: ios/RipidStaging.xcodeproj
          p12-base64: ${{ secrets.IOS_STAGING_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_STAGING_PROVISION_BASE64 }}
          code-signing-identity: 'iPhone Distribution'
          team-id: ${{ secrets.IOS_STAGING_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_STAGING_CERTIFICATE_PASSWORD }}
          workspace-path: ios/RipidStaging.xcworkspace
          scheme: RipidStaging

      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: 'output.ipa'
          issuer-id: ${{ secrets.APPSTORE_STAGING_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_STAGING_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_STAGING_API_PRIVATE_KEY }}